learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
from django.urls import path

from . import views

app_name='learning_logs'

urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    #show topics
    path('topics/', views.topics, name='topics'),
    #show spcified topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Add new webpage
    path('new_topic/', views.new_topic, name='new_topic'),
    # New entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Edit existed entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.urls import path, include
# from . import views

app_name='users'

urlpatterns = [
    # Default
    path('', include('django.contrib.auth.urls')),

]

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """Themes for learning."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return to the texts"""
        return self.text


class Entry(models.Model):
    """Knowledges on the specified topic"""
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return to the texts"""
        if len(str(self.text)) > 50:
            return '{}...'.format(str(self.text[:50]))
        else:
            return self.text
        

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from .models import Topic, Entry
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    """Home Page"""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """Get topics"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    """Show the details of specified topic"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries':entries}
    return render(request, 'learning_logs/topic.html', context)

def new_topic(request):
    """Add new topic"""
    if request.method != 'POST':
        # Not submmited : Create new table
        form = TopicForm()
    else:
        # Deal with submmited data
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

def new_entry(request, topic_id):
    """Add item in the topic"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # Submmit an empty table if no data
        form = EntryForm()
    else:
        #Get data from POST, Deal with it
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

def edit_entry(request, entry_id):
    """Edit existed entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        # Initialize
        form = EntryForm(instance=entry)
    else:
        #Get data from POST, deal with it
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)


users/views.py
from django.shortcuts import render

# Create your views here.

learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Logs</a> -
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
    {% if user.is_authenticated %}
    Hello , {{ user.name }}.
    <a href="{% url 'users:logged_out' %}">Log out</a>
    {% else %}
    <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</p>

    <p>Edit Entry:</p>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>
    
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}


{% block content %}
    <p>Learning, enjoying, your life</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="Submmit">Add Entry</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}
<p>Add a new topic:</p>
<form action="{% url 'learning_logs:new_topic' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="Submmit">add topic</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <p>Topic: {{ topic }}</p>

    <p>Entries:</p>
    
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id%}">Add new entry</a>
    </p>

    <ul>
        {% for entry in entries %}
            <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
            <p>
                <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
            </p>
            </li>
            {% empty %}
            <li>
            No Entries Yet.
            </li>
        {% endfor %}
    </ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>Topics</p>

<ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'learning_logs:topic' topic.id%}">{{ topic }}</a>
        </li>
    {% empty %}
        <li>No topics to show.</li>
    {% endfor %}
</ul>

<a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>

{% endblock content %}